# Generated by Django 5.0.3 on 2025-11-20 21:30

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=150, verbose_name='Nombre Marca')),
                ('tipo_produccion', models.CharField(choices=[('artesanal', 'Artesanal'), ('semi_industrial', 'Semi Industrial'), ('servicio', 'Servicio')], max_length=25, verbose_name='Tipo de Produccion')),
                ('nivel_emprendimiento', models.CharField(choices=[('idea_inicial', 'Idea Inicial'), ('produccion_pequena_escala', 'Produccion Pequeña Escala'), ('produccion_habilitada', 'Produccion Habilitada/Formalizada'), ('escalamiento_productivo', 'Escalamiento Productivo'), ('comercializacion_exportacion', 'Comercializacion en Gondolas / Exportacion')], default='idea_inicial', max_length=50, verbose_name='Nivel Actual del Emprendimiento')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
            },
        ),
        migrations.CreateModel(
            name='ModalidadDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Personas Involucradas')),
                ('tipo_modalidad_trabajo', models.CharField(choices=[('individual', 'Individual'), ('familiar', 'Familiar'), ('asociativo_cooperativo', 'Asociativo / Cooperativo')], max_length=50, verbose_name='Tipo')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidad_trabajo', to='emprendimiento.emprendimiento')),
            ],
            options={
                'verbose_name': 'Modalidad De Trabajo',
                'verbose_name_plural': 'Modalidades De Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rubro', 'Rubro'), ('subrubro', 'Subrubro')], default='subrubro', max_length=8)),
                ('nombre', models.CharField(help_text='Ejemplo: Gastronomia', max_length=100, verbose_name='Nombre')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Ejemplo: Gastronomia', null=True, on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.rubro', verbose_name='Rubro Padre')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_personas', to='emprendimiento.rubro'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('subservicio', 'Subservicio')], default='subservicio', max_length=11)),
                ('nombre', models.CharField(help_text='Ejemplo: Gastronomia', max_length=100, verbose_name='Nombre')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Ejemplo: Gastronomia', null=True, on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.servicio', verbose_name='Servicio Padre')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_personas', to='emprendimiento.servicio'),
        ),
        migrations.AddConstraint(
            model_name='rubro',
            constraint=models.UniqueConstraint(fields=('nombre', 'parent'), name='unique_rubro'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('nombre', 'parent'), name='unique_servicio'),
        ),
    ]
