# Generated by Django 5.0.3 on 2026-03-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0002_alter_emprendedor_persona'),
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='emprendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprendimientos', to='emprendedor.emprendedor'),
        ),
    ]
