# Generated by Django 5.0.3 on 2026-03-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0002_emprendimiento_emprendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_emprendimiento', to='emprendimiento.rubro'),
        ),
    ]
