# Generated by Django 5.0.3 on 2026-03-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0003_emprendedor_email'),
        ('emprendimiento', '0003_alter_emprendimiento_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendimiento',
            name='emprendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprendimientos', to='emprendedor.emprendedor'),
        ),
    ]
