# Generated by Django 5.0.3 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0004_alter_emprendimiento_emprendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
