# Generated by Django 5.0.3 on 2026-04-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0005_emprendimiento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo')),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='emprendimiento.emprendimiento')),
            ],
        ),
    ]
