"""
Django settings for settings settings.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import sys
import environ

CORS_ORIGIN_ALLOW_ALL = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-api-key',
]


ROOT_DIR = environ.Path(__file__) - 3
PROJECT_DIR = ROOT_DIR.path('project')
APPS_DIR = PROJECT_DIR.path('apps')

sys.path.insert(0, str(APPS_DIR))

# Load operating system environment variables and then prepare to use them
env = environ.Env()
#  patch for https://github.com/joke2k/django-environ/issues/119
env_file = str(ROOT_DIR.path('.env'))
env.read_env(env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')
#SECRET_KEY = env('DJANGO_SECRET_KEY', default='CHANGEME!!!' if DEBUG else None)

# API Key para acceso a las APIs
API_KEY = env('API_KEY')




# PROJECT
PROJECT_NAME_HEADER = env('PROJECT_NAME_HEADER', default='Django')
PROJECT_NAME_TITLE = env('PROJECT_NAME_TITLE', default='Django')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default='*')  # noqa

# Application definition

DJANGO_APPS = [
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres'
]

THIRD_PARTY_APPS = [
    'mptt',
    'oauth2_provider',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'dal',
    'dal_queryset_sequence',
    'dal_select2',
    'rest_framework_social_oauth2',
    'django_better_admin_arrayfield',
    'mozilla_django_oidc',
    'storages',
]

PROJECT_APPS = [
    'usuario',
    'core',
    'persona',
    'util',
    'emprendimiento',
    'emprendedor',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'
JET_DEFAULT_THEME = 'light-blue'
JET_SIDE_MENU_COMPACT = True

ROOT_URLCONF = 'project.urls'

AUTH_USER_MODEL = 'usuario.Usuario'

DATABASES = {'default': env.db('DATABASE_URL')}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(PROJECT_DIR.path('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LOCALE_PATHS = [str(PROJECT_DIR.path('translations'))]

LANGUAGE_CODE = env.str('DJANGO_LANGUAGE_CODE', default='es')

TIME_ZONE = env.str('DJANGO_TIME_ZONE', default='America/Argentina/Catamarca')

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = env('DJANGO_STATIC_URL', default='/static/')

STATIC_ROOT = env('DJANGO_STATIC_ROOT', default='./static/')

STATICFILES_DIRS = [str(PROJECT_DIR.path('assets')), ]

if "DJANGO_GDAL_LIBRARY_PATH" in env.ENVIRON:
    GDAL_LIBRARY_PATH = env('DJANGO_GDAL_LIBRARY_PATH')
if "DJANGO_GEOS_LIBRARY_PATH" in env.ENVIRON:
    GEOS_LIBRARY_PATH = env('DJANGO_GEOS_LIBRARY_PATH')

AUTHENTICATION_BACKENDS = (
    'rest_framework_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'usuario.oidc.CustomOIDCAuthenticationBackend',
)

REST_FRAMEWORK = {
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'util.paginations.LargePagination',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework_json_api.parsers.JSONParser',
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework_social_oauth2.authentication.SocialAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'util.permissions.HasApiKey',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework_json_api.metadata.JSONAPIMetadata',
    'NON_FIELD_ERRORS_KEY': 'error_messages'
}

ACTIVAR_HERRAMIENTAS_DEBUGGING = env.bool('ACTIVAR_HERRAMIENTAS_DEBUGGING', default=False)
if ACTIVAR_HERRAMIENTAS_DEBUGGING:
    INTERNAL_IPS = ['127.0.0.1']
    INSTALLED_APPS += ('debug_toolbar', 'django_extensions')
    MIDDLEWARE += ('debug_toolbar.middleware.DebugToolbarMiddleware',)
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] += ('rest_framework.renderers.BrowsableAPIRenderer',)
    REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] += ('rest_framework.authentication.SessionAuthentication',)

DRFSO2_URL_NAMESPACE = 'auth-api'
if "DJANGO_CSRF" in env.ENVIRON:
    CSRF_TRUSTED_ORIGINS = env("DJANGO_CSRF").split(" ")



# Configuración del Proveedor OIDC 
OIDC_RP_CLIENT_ID = env.str('OIDC_CLIENT_ID')   # ID del cliente
OIDC_RP_CLIENT_SECRET = env.str('OIDC_CLIENT_SECRET')  # Secreto

# Endpoints del proveedor
#OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://tu-proveedor.com/authorize'
#OIDC_OP_TOKEN_ENDPOINT = 'https://tu-proveedor.com/token'
#OIDC_OP_USER_ENDPOINT = 'https://tu-proveedor.com/userinfo'

# Discovery
#OIDC_OP_DISCOVERY_DOCUMENT_URL = 'https://develop-api-mi.catamarca.gob.ar/openid/.well-known/openid-configuration'

# Endpoints manuales (copiados de tu JSON)
OIDC_OP_AUTHORIZATION_ENDPOINT = "https://develop-api-mi.catamarca.gob.ar/openid/authorize"
OIDC_OP_TOKEN_ENDPOINT = "https://develop-api-mi.catamarca.gob.ar/openid/token"
OIDC_OP_USER_ENDPOINT = "https://develop-api-mi.catamarca.gob.ar/openid/userinfo"
OIDC_OP_JWKS_ENDPOINT = 'https://develop-api-mi.catamarca.gob.ar/openid/jwks'
# Opcional: para logout
# OIDC_OP_LOGOUT_ENDPOINT = "https://develop-api-mi.catamarca.gob.ar/openid/end-session"


# scopes 
OIDC_RP_SCOPES = 'openid email profile'

# Forzar login en el proveedor
OIDC_AUTH_REQUEST_EXTRA_PARAMS = {'prompt': 'login'}

# 6. Creación automática de usuarios
OIDC_CREATE_USER = True 

# Redirecciones
LOGIN_URL = 'oidc_authentication_init'
#LOGIN_REDIRECT_URL = '/'  
LOGIN_REDIRECT_URL = '/admin/'                 
LOGOUT_REDIRECT_URL = '/'    

OIDC_VERIFY_SSL = False
OIDC_RP_SIGN_ALGO = 'RS256'
SESSION_SAVE_EVERY_REQUEST = True

# Cachear la verificación del token OIDC para no llamar al servidor OIDC en cada request.
# El backend de DRF valida el Bearer token contra /userinfo; con caché evitamos
# el flood de requests y el InsecureRequestWarning en cada hit a la API.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 300,  # 5 minutos
    }
}
# mozilla_django_oidc usará el caché de Django para almacenar los claims del token
OIDC_CACHE_ACCESS_TOKENS = True
# Suprimir warnings de SSL en desarrollo (el servidor OIDC usa cert no verificable)
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'mozilla_django_oidc': {
            'handlers': ['console'],
            'level': 'WARNING',  # era DEBUG, reducir verbosidad
        },
    },
}

# Usar storage de S3 (compatible con MinIO)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Credenciales de MinIO (las que usaste en docker run)
MINIO_ACCESS_KEY = 'minioadmin'
MINIO_SECRET_KEY = 'minioadmin'

# Configuración AWS/S3

#AWS_ACCESS_KEY_ID = env.str('MINIO_ACCESS_KEY', 'minioadmin')
AWS_ACCESS_KEY_ID = env('MINIO_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = env.str('MINIO_SECRET_KEY', 'minioadmin')
AWS_STORAGE_BUCKET_NAME = env.str('MINIO_BUCKET_NAME', 'economiasocial')


AWS_S3_ENDPOINT_URL = 'http://localhost:9000'

# Configuraciones para MinIO (local, sin SSL)
AWS_S3_USE_SSL = False
AWS_S3_VERIFY = False
AWS_S3_REGION_NAME = 'us-east-1'  # MinIO no lo usa, pero es requerido

# Configuración de URLs y permisos
AWS_DEFAULT_ACL = 'private'  # Archivos privados por defecto
AWS_QUERYSTRING_AUTH = True  # URLs firmadas (recomendado para desarrollo)
AWS_QUERYSTRING_EXPIRE = 3600  # Expiración de URLs firmadas en segundos (1 hora)

# Opcional: si quieres organizar mejor los archivos, puedes definir:
AWS_LOCATION = 'documentos'  # Esto creará una subcarpeta dentro del bucket
# Si usas AWS_LOCATION, el upload_to del modelo se concatenará automáticamente

