# Generated by Django 5.0.3 on 2026-02-26 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0003_persona_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Efectivo', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SituacionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Monotributista', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Situacion Fiscal',
                'verbose_name_plural': 'Situaciones Fiscales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor', to='persona.persona')),
                ('medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor_medio_de_pago', to='emprendedor.mediodepago')),
                ('situacion_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor_situacion_fiscal', to='emprendedor.situacionfiscal')),
            ],
            options={
                'verbose_name': 'Emprendedor',
                'verbose_name_plural': 'Emprendedores',
                'ordering': ['-id'],
            },
        ),
    ]
