# Generated by Django 5.0.3 on 2026-02-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0001_initial'),
        ('persona', '0003_persona_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor_persona', to='persona.persona'),
        ),
    ]
