# Generated by Django 5.0.3 on 2026-03-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0002_alter_emprendedor_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
