# Generated by Django 5.0.3 on 2026-04-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0003_emprendedor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManipulaAlimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carnet', models.CharField(max_length=20, null=True, verbose_name='Numero Carnet')),
                ('vencimiento_carnet', models.DateField(null=True, verbose_name='Vencimiento Carnet')),
                ('numero_habilitacion_bromatologica', models.CharField(max_length=20, null=True, verbose_name='Numero Habilitacion Bromatologica')),
                ('vencimiento_habilitacion_bromatologica', models.DateField(null=True, verbose_name='Vencimiento Habilitacion Bromatologica')),
            ],
            options={
                'verbose_name': 'Manipula Alimentos',
                'verbose_name_plural': 'Manipulan Alimentos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='participa_ferias',
            field=models.BooleanField(default=False, verbose_name='Participa en Ferias'),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='participa_mercado_itinerante',
            field=models.BooleanField(default=False, verbose_name='Participa en Mercado Itinerante'),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='manipula_alimentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprendedor_manipula_alimentos', to='emprendedor.manipulaalimentos'),
        ),
    ]
