# Generated by Django 5.0.3 on 2026-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0004_manipulaalimentos_emprendedor_participa_ferias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='interes_compras_publicas',
            field=models.BooleanField(default=False, verbose_name='Interes en Compras Publicas'),
        ),
    ]
