# Generated by Django 5.0.3 on 2026-04-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendedor', '0005_emprendedor_interes_compras_publicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_emprendedor/', verbose_name='Archivo')),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='emprendedor.emprendedor')),
            ],
        ),
    ]
